[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn src.api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { SERVICE_NAME = "goalgetter-client-prod", LOG_LEVEL = "INFO" }

[environments.staging]
variables = { SERVICE_NAME = "goalgetter-client-staging", LOG_LEVEL = "DEBUG" }
